"""Performance metrics for completed backtests."""

from backtester.metrics.performance import (
    alpha_beta,
    annualized_return,
    buy_and_hold_equity,
    best_worst_day,
    conditional_value_at_risk,
    drawdown_duration_days,
    excess_returns,
    generate_report,
    information_ratio,
    max_drawdown,
    monthly_returns,
    print_report,
    profit_factor,
    rolling_drawdown,
    rolling_sharpe_ratio,
    rolling_volatility,
    sharpe_ratio,
    sortino_ratio,
    total_return,
    value_at_risk,
    win_rate,
)
from backtester.metrics.trades import TradePair, pair_trades, trade_summary

__all__ = [
    "TradePair",
    "alpha_beta",
    "annualized_return",
    "best_worst_day",
    "buy_and_hold_equity",
    "conditional_value_at_risk",
    "drawdown_duration_days",
    "excess_returns",
    "generate_report",
    "information_ratio",
    "max_drawdown",
    "monthly_returns",
    "pair_trades",
    "print_report",
    "profit_factor",
    "rolling_drawdown",
    "rolling_sharpe_ratio",
    "rolling_volatility",
    "sharpe_ratio",
    "sortino_ratio",
    "trade_summary",
    "total_return",
    "value_at_risk",
    "win_rate",
]
